import { and, asc, desc, eq } from 'drizzle-orm';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

import { db } from '@/core/db';
import { closePostgresDb } from '@/core/db/postgres';
import { navCategory, navItem, user } from '@/config/db/schema';

const DEMO_USER = {
  id: 'demo-navigation-user',
  name: 'Demo Navigation',
  email: 'demo-navigation@shipany.ai',
  emailVerified: true,
  image: '',
  utmSource: 'seed',
  ip: '',
  locale: 'en',
};

function sqlString(value: string | null | undefined) {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlBoolean(value: boolean | null | undefined) {
  if (value === null || value === undefined) {
    return 'FALSE';
  }

  return value ? 'TRUE' : 'FALSE';
}

function sqlNumber(value: number | null | undefined) {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  return String(value);
}

function sqlTimestamp(value: Date | string | number | null | undefined) {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  const date = value instanceof Date ? value : new Date(value);
  return sqlString(date.toISOString());
}

async function main() {
  const categories = await db()
    .select()
    .from(navCategory)
    .where(eq(navCategory.status, 'active'))
    .orderBy(asc(navCategory.sort), asc(navCategory.slug));

  const items = await db()
    .select()
    .from(navItem)
    .where(eq(navItem.status, 'live'))
    .orderBy(desc(navItem.isFeatured), desc(navItem.createdAt), asc(navItem.slug));

  const lines: string[] = [];

  lines.push('-- Generated by scripts/export-navigation-sql.ts');
  lines.push('-- Import this file into the configured PostgreSQL database.');
  lines.push('BEGIN;');
  lines.push('');
  lines.push('-- Seed demo owner user for nav_item.user_id foreign key');
  lines.push(
    `INSERT INTO "user" ("id", "name", "email", "email_verified", "image", "created_at", "updated_at", "utm_source", "ip", "locale") VALUES (${sqlString(DEMO_USER.id)}, ${sqlString(DEMO_USER.name)}, ${sqlString(DEMO_USER.email)}, ${sqlBoolean(DEMO_USER.emailVerified)}, ${sqlString(DEMO_USER.image)}, NOW(), NOW(), ${sqlString(DEMO_USER.utmSource)}, ${sqlString(DEMO_USER.ip)}, ${sqlString(DEMO_USER.locale)})`
  );
  lines.push('ON CONFLICT ("id") DO UPDATE SET');
  lines.push('  "name" = EXCLUDED."name",');
  lines.push('  "email" = EXCLUDED."email",');
  lines.push('  "email_verified" = EXCLUDED."email_verified",');
  lines.push('  "image" = EXCLUDED."image",');
  lines.push('  "updated_at" = NOW(),');
  lines.push('  "utm_source" = EXCLUDED."utm_source",');
  lines.push('  "ip" = EXCLUDED."ip",');
  lines.push('  "locale" = EXCLUDED."locale";');
  lines.push('');

  if (items.length > 0) {
    const itemIds = items.map((item: any) => sqlString(item.id)).join(', ');
    lines.push('-- Remove existing seed nav items before re-import');
    lines.push(`DELETE FROM "nav_item" WHERE "id" IN (${itemIds});`);
    lines.push('');
  }

  if (categories.length > 0) {
    const categoryIds = categories.map((item: any) => sqlString(item.id)).join(', ');
    lines.push('-- Remove existing seed nav categories before re-import');
    lines.push(`DELETE FROM "nav_category" WHERE "id" IN (${categoryIds});`);
    lines.push('');
  }

  if (categories.length > 0) {
    lines.push('-- Navigation categories');
    lines.push(
      `INSERT INTO "nav_category" ("id", "name", "slug", "icon", "status", "sort", "created_at", "updated_at") VALUES`
    );
    lines.push(
      categories
        .map(
          (item: any) =>
            `  (${sqlString(item.id)}, ${sqlString(item.name)}, ${sqlString(item.slug)}, ${sqlString(item.icon)}, ${sqlString(item.status)}, ${sqlNumber(item.sort)}, ${sqlTimestamp(item.createdAt)}, ${sqlTimestamp(item.updatedAt)})`
        )
        .join(',\n') + ';'
    );
    lines.push('');
  }

  if (items.length > 0) {
    lines.push('-- Navigation items');
    lines.push(
      `INSERT INTO "nav_item" ("id", "user_id", "name", "slug", "tagline", "description", "logo_url", "url", "thumbnail_url", "pricing_model", "discount_code", "github_url", "status", "is_featured", "is_affiliate", "categories", "created_at", "updated_at") VALUES`
    );
    lines.push(
      items
        .map(
          (item: any) =>
            `  (${sqlString(item.id)}, ${sqlString(DEMO_USER.id)}, ${sqlString(item.name)}, ${sqlString(item.slug)}, ${sqlString(item.tagline)}, ${sqlString(item.description)}, ${sqlString(item.logoUrl)}, ${sqlString(item.url)}, ${sqlString(item.thumbnailUrl)}, ${sqlString(item.pricingModel)}, ${sqlString(item.discountCode)}, ${sqlString(item.githubUrl)}, ${sqlString(item.status)}, ${sqlBoolean(item.isFeatured)}, ${sqlBoolean(item.isAffiliate)}, ${sqlString(item.categories)}, ${sqlTimestamp(item.createdAt)}, ${sqlTimestamp(item.updatedAt)})`
        )
        .join(',\n') + ';'
    );
    lines.push('');
  }

  lines.push('COMMIT;');
  lines.push('');

  const outputPath = path.resolve(process.cwd(), 'db/navigation.seed.sql');
  writeFileSync(outputPath, lines.join('\n'));

  console.log(
    `Exported ${categories.length} nav categories and ${items.length} nav items to ${outputPath}`
  );
}

main()
  .catch((error) => {
    console.error('Export navigation SQL failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closePostgresDb().catch(() => undefined);
  });
