/* eslint-disable */
// This file is auto-generated by scripts/generate-world-models-content.mjs.
// Do not edit manually.

export const worldModelsContent = {
  "topics": [
    {
      "slug": "agentic-planning",
      "name_en": "Agentic Planning",
      "name_zh": "智能体规划",
      "description_en": "Long-horizon reasoning and planning with learned environment models.",
      "description_zh": "利用学习到的环境模型进行长时推理与规划。",
      "hero_en": "World models become useful when they improve planning.",
      "hero_zh": "世界模型在提升规划能力时才真正产生价值。",
      "featured": false
    },
    {
      "slug": "driving-world-models",
      "name_en": "Driving World Models",
      "name_zh": "自动驾驶世界模型",
      "description_en": "World models for autonomous driving simulation, forecasting, and closed-loop testing.",
      "description_zh": "面向自动驾驶仿真、预测与闭环测试的世界模型。",
      "hero_en": "Simulation and forecasting for autonomous driving systems.",
      "hero_zh": "面向自动驾驶系统的仿真与预测。",
      "featured": true
    },
    {
      "slug": "embodied-world-models",
      "name_en": "Embodied World Models",
      "name_zh": "具身世界模型",
      "description_en": "World models for agents that act through bodies in the physical world.",
      "description_zh": "服务于具身智能体在物理世界中行动与规划的世界模型。",
      "hero_en": "Planning and simulation for embodied agents.",
      "hero_zh": "面向具身智能体的规划与模拟。",
      "featured": true
    },
    {
      "slug": "game-environment-world-models",
      "name_en": "Game and Environment World Models",
      "name_zh": "游戏与环境世界模型",
      "description_en": "Interactive environment models inspired by games and synthetic worlds.",
      "description_zh": "受游戏和合成环境启发的交互式环境模型。",
      "hero_en": "Games are proving grounds for world-model interfaces.",
      "hero_zh": "游戏是世界模型交互能力的重要试验场。",
      "featured": true
    },
    {
      "slug": "robotics-world-models",
      "name_en": "Robotics World Models",
      "name_zh": "机器人世界模型",
      "description_en": "World-model approaches tailored to robotic manipulation and control.",
      "description_zh": "聚焦机器人操作、控制与长时规划的世界模型方法。",
      "hero_en": "Robotics needs simulation, prediction, and controllable planning.",
      "hero_zh": "机器人需要模拟、预测与可控规划。",
      "featured": true
    },
    {
      "slug": "video-world-models",
      "name_en": "Video World Models",
      "name_zh": "视频世界模型",
      "description_en": "Models that predict or generate coherent video futures and interactive scenes.",
      "description_zh": "关注视频未来预测、可交互场景生成与长时视频建模的方向。",
      "hero_en": "From video prediction to interactive generated environments.",
      "hero_zh": "从视频预测到可交互生成环境。",
      "featured": true
    },
    {
      "slug": "world-models",
      "name_en": "World Models",
      "name_zh": "世界模型",
      "description_en": "General research on models that simulate or predict world dynamics.",
      "description_zh": "围绕环境动态建模、预测与模拟的总体研究方向。",
      "hero_en": "Track the core papers, systems, and product signals shaping the world-models field.",
      "hero_zh": "追踪塑造世界模型领域的核心论文、系统与产业信号。",
      "featured": true
    }
  ],
  "papers": [
    {
      "slug": "embodied-intelligence-simulators-world-models-survey",
      "title_en": "A Survey: Learning Embodied Intelligence from Physical Simulators and World Models",
      "title_zh": "综述：从物理模拟器与世界模型中学习具身智能",
      "abstract_en": "This survey reviews how physical simulators and world models jointly support embodied intelligence, robot learning, and sim-to-real transfer.",
      "abstract_zh": "这篇综述回顾了物理模拟器与世界模型如何共同支撑具身智能、机器人学习以及 sim-to-real 迁移。",
      "authors": [
        "Xiaoxiao Long",
        "Qingrui Zhao",
        "Kaiwen Zhang",
        "Zihao Zhang",
        "Dingrui Wang",
        "Yumeng Liu",
        "Zhengjie Shu",
        "Yi Lu",
        "Shouzheng Wang",
        "Xinzhe Wei",
        "Wei Li",
        "Wei Yin",
        "Yao Yao",
        "Jia Pan",
        "Qiu Shen",
        "Ruigang Yang",
        "Xun Cao",
        "Qionghai Dai"
      ],
      "affiliations": [
        "Multiple Institutions"
      ],
      "source_url": "https://arxiv.org/abs/2507.00917",
      "paper_venue": "arXiv",
      "publication_date": "2025-07-01",
      "year": 2025,
      "project_url": "https://github.com/NJU3DV-LoongGroup/Embodied-World-Models-Survey",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "capabilities": [
        "prediction",
        "planning",
        "simulation"
      ],
      "scenarios": [
        "robotics",
        "research-platforms"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "适合作为具身世界模型的总览入口，覆盖模拟器、内部模型和真实部署之间的关系。",
      "editorial_summary_en": "A strong overview of how simulators and internal world models combine in embodied AI.",
      "why_it_matters": "It helps readers understand the broader stack around embodied world models, not just individual robot demos.",
      "related_project_slugs": [],
      "related_update_slugs": [
        "embodied-intelligence-survey-published"
      ],
      "related_timeline_event_slugs": [
        "embodied-intelligence-survey-milestone"
      ],
      "featured": false
    },
    {
      "slug": "iclr-2025-world-models-workshop",
      "title_en": "ICLR 2025 Workshop on World Models",
      "title_zh": "ICLR 2025 世界模型研讨会",
      "abstract_en": "A workshop signaling the field’s consolidation and breadth.",
      "abstract_zh": "标志世界模型方向逐渐成型并扩展的研讨会节点。",
      "authors": [
        "Workshop Organizers"
      ],
      "affiliations": [
        "ICLR"
      ],
      "source_url": "https://openreview.net/group?id=ICLR.cc/2025/Workshop/World_Models",
      "paper_venue": "OpenReview",
      "publication_date": "2025-04-20",
      "year": 2025,
      "topics": [
        "world-models",
        "agentic-planning",
        "embodied-world-models"
      ],
      "capabilities": [
        "prediction",
        "planning",
        "simulation"
      ],
      "scenarios": [
        "research-platforms",
        "agents",
        "robotics"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "说明世界模型已经从零散论文进入专题化社区阶段。",
      "editorial_summary_en": "Shows the field maturing into a dedicated research community.",
      "why_it_matters": "Workshops are a good signal that a topic has become durable enough for a specialized site.",
      "related_project_slugs": [],
      "related_update_slugs": [
        "iclr-2025-workshop"
      ],
      "related_timeline_event_slugs": [
        "iclr-workshop"
      ],
      "featured": false
    },
    {
      "slug": "gaia-2",
      "title_en": "GAIA-2: A Controllable Multi-View Generative World Model for Autonomous Driving",
      "title_zh": "GAIA-2：面向自动驾驶的可控多视角生成式世界模型",
      "abstract_en": "GAIA-2 extends generative driving world models with stronger controllability, multi-view consistency, and richer scenario synthesis for autonomy evaluation.",
      "abstract_zh": "GAIA-2 强化了自动驾驶生成式世界模型的可控性、多视角一致性与复杂场景合成能力，用于自动驾驶评测与训练。",
      "authors": [
        "Wayve"
      ],
      "affiliations": [
        "Wayve"
      ],
      "source_url": "https://wayve.ai/wp-content/uploads/2025/03/GAIA_2_Technical_Report.pdf",
      "paper_venue": "Wayve Technical Report",
      "publication_date": "2025-03-26",
      "year": 2025,
      "project_url": "https://wayve.ai/thinking/gaia-2/",
      "topics": [
        "world-models",
        "driving-world-models"
      ],
      "capabilities": [
        "prediction",
        "simulation",
        "controllable-environment-generation"
      ],
      "scenarios": [
        "autonomous-driving",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "把 GAIA-1 从概念验证推进到更可控、更接近生产级自动驾驶仿真平台。",
      "editorial_summary_en": "Moves GAIA from an early showcase to a more controllable driving-world-model stack.",
      "why_it_matters": "It shows how world models are becoming core infrastructure for generating, stress-testing, and evaluating edge-case driving scenarios at scale.",
      "related_project_slugs": [
        "gaia-2-project"
      ],
      "related_update_slugs": [
        "gaia-2-release"
      ],
      "related_timeline_event_slugs": [
        "gaia-2-milestone"
      ],
      "featured": true
    },
    {
      "slug": "groot-n1",
      "title_en": "NVIDIA Isaac GR00T N1: An Open Foundation Model for Humanoid Robots",
      "title_zh": "NVIDIA Isaac GR00T N1：面向人形机器人的开放基础模型",
      "abstract_en": "GR00T N1 is NVIDIA's open humanoid robot foundation model, positioned as a general policy and reasoning stack for robot skills and transfer.",
      "abstract_zh": "GR00T N1 是 NVIDIA 推出的人形机器人开放基础模型，被定位为面向机器人技能与迁移的通用策略和推理栈。",
      "authors": [
        "NVIDIA"
      ],
      "affiliations": [
        "NVIDIA"
      ],
      "source_url": "https://research.nvidia.com/publication/2025-03_nvidia-isaac-gr00t-n1-open-foundation-model-humanoid-robots",
      "paper_venue": "NVIDIA Research",
      "publication_date": "2025-03-17",
      "year": 2025,
      "project_url": "https://developer.nvidia.com/blog/accelerate-generalist-humanoid-robot-development-with-nvidia-isaac-gr00t-n1/",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "capabilities": [
        "planning",
        "simulation",
        "prediction"
      ],
      "scenarios": [
        "robotics",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "把世界模型、VLA 和物理 AI 基础设施进一步合流到人形机器人路线中。",
      "editorial_summary_en": "A strong signal that world-model-style infrastructure is converging with humanoid robotics.",
      "why_it_matters": "It links world modeling, simulation, and robot policy transfer into a practical platform story for embodied AI.",
      "related_project_slugs": [
        "groot-n1-project"
      ],
      "related_update_slugs": [
        "groot-n1-launch"
      ],
      "related_timeline_event_slugs": [
        "groot-n1-milestone"
      ],
      "featured": true
    },
    {
      "slug": "gemini-robotics",
      "title_en": "Gemini Robotics and Gemini Robotics-ER",
      "title_zh": "Gemini Robotics 与 Gemini Robotics-ER",
      "abstract_en": "Google DeepMind introduces Gemini Robotics and Gemini Robotics-ER as embodied reasoning and robot-control models for physical agents.",
      "abstract_zh": "Google DeepMind 推出 Gemini Robotics 与 Gemini Robotics-ER，作为面向物理智能体的具身推理与机器人控制模型。",
      "authors": [
        "Google DeepMind"
      ],
      "affiliations": [
        "Google DeepMind"
      ],
      "source_url": "https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/",
      "paper_venue": "DeepMind Blog",
      "publication_date": "2025-03-12",
      "year": 2025,
      "project_url": "https://deepmind.google/technologies/gemini-robotics/",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models",
        "agentic-planning"
      ],
      "capabilities": [
        "planning",
        "prediction",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "robotics",
        "agents",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "把具身推理、长程任务分解和机器人执行统一到 Gemini 体系里。",
      "editorial_summary_en": "Brings embodied reasoning, planning, and robot execution into the Gemini stack.",
      "why_it_matters": "It shows major labs treating world understanding and planning as central ingredients for physical agents, not separate add-ons.",
      "related_project_slugs": [
        "gemini-robotics-project"
      ],
      "related_update_slugs": [
        "gemini-robotics-launch"
      ],
      "related_timeline_event_slugs": [
        "gemini-robotics-milestone"
      ],
      "featured": true
    },
    {
      "slug": "embodied-world-model-survey",
      "title_en": "Embodied World Models: A Survey",
      "title_zh": "具身世界模型综述",
      "abstract_en": "A survey of world-model techniques for embodied agents and robotics.",
      "abstract_zh": "综述具身智能体与机器人中的世界模型技术。",
      "authors": [
        "Multiple Authors"
      ],
      "affiliations": [
        "Academic"
      ],
      "source_url": "https://arxiv.org/abs/2501.00001",
      "paper_venue": "arXiv",
      "publication_date": "2025-01-15",
      "year": 2025,
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "capabilities": [
        "prediction",
        "planning"
      ],
      "scenarios": [
        "robotics",
        "agents",
        "research-platforms"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "帮助读者快速建立具身世界模型的全景认知。",
      "editorial_summary_en": "A useful overview of embodied world-model methods.",
      "why_it_matters": "Survey papers help new readers enter the topic quickly.",
      "related_project_slugs": [
        "cosmos-platform"
      ],
      "related_update_slugs": [
        "embodied-survey-published"
      ],
      "related_timeline_event_slugs": [
        "embodied-survey"
      ],
      "featured": false
    },
    {
      "slug": "cosmos-world-foundation-models",
      "title_en": "Cosmos World Foundation Models",
      "title_zh": "Cosmos 世界基础模型",
      "abstract_en": "A platform direction for physical-AI world models spanning robotics and driving.",
      "abstract_zh": "面向机器人与自动驾驶的 Physical AI 世界模型平台方向。",
      "authors": [
        "NVIDIA"
      ],
      "affiliations": [
        "NVIDIA"
      ],
      "source_url": "https://www.nvidia.com/en-us/ai/cosmos/",
      "paper_venue": "NVIDIA",
      "publication_date": "2025-01-06",
      "year": 2025,
      "project_url": "https://www.nvidia.com/en-us/ai/cosmos/",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models",
        "driving-world-models"
      ],
      "capabilities": [
        "simulation",
        "prediction",
        "planning"
      ],
      "scenarios": [
        "robotics",
        "autonomous-driving",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "把世界模型正式推向 Physical AI 的基础设施层。",
      "editorial_summary_en": "Turns world models into infrastructure for physical AI.",
      "why_it_matters": "Signals that world models are becoming platform primitives for robotics and autonomy.",
      "related_project_slugs": [
        "cosmos-platform"
      ],
      "related_update_slugs": [
        "cosmos-platform-launch"
      ],
      "related_timeline_event_slugs": [
        "cosmos-launch"
      ],
      "featured": true
    },
    {
      "slug": "genie-2",
      "title_en": "Genie 2: A large-scale foundation world model",
      "title_zh": "Genie 2：大规模基础世界模型",
      "abstract_en": "Genie 2 explores interactive, controllable environment generation at scale.",
      "abstract_zh": "Genie 2 探索了大规模、可交互、可控的环境生成。",
      "authors": [
        "Google DeepMind"
      ],
      "affiliations": [
        "Google DeepMind"
      ],
      "source_url": "https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/",
      "paper_venue": "DeepMind Blog",
      "publication_date": "2024-12-04",
      "year": 2024,
      "project_url": "https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/",
      "topics": [
        "world-models",
        "video-world-models",
        "game-environment-world-models"
      ],
      "capabilities": [
        "simulation",
        "controllable-environment-generation"
      ],
      "scenarios": [
        "gaming",
        "video-generation",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "把世界模型从预测器推进到可交互环境生成器。",
      "editorial_summary_en": "Pushes world models toward interactive generated environments.",
      "why_it_matters": "It reframes world models as a usable interface for simulation and agent training.",
      "related_project_slugs": [
        "genie-2-project"
      ],
      "related_update_slugs": [
        "genie-2-release"
      ],
      "related_timeline_event_slugs": [
        "genie-2-milestone"
      ],
      "featured": true
    },
    {
      "slug": "movie-gen",
      "title_en": "Movie Gen: A Cast of Media Foundation Models",
      "title_zh": "Movie Gen：一组媒体基础模型",
      "abstract_en": "Movie Gen presents a family of large media foundation models for high-quality video generation, editing, personalization, and synchronized audio synthesis.",
      "abstract_zh": "Movie Gen 提出了一组大型媒体基础模型，用于高质量视频生成、编辑、个性化和同步音频合成。",
      "authors": [
        "Meta"
      ],
      "affiliations": [
        "Meta"
      ],
      "source_url": "https://arxiv.org/abs/2410.13720",
      "paper_venue": "arXiv",
      "publication_date": "2024-10-17",
      "year": 2024,
      "project_url": "https://go.fb.me/MovieGenResearchVideos",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "capabilities": [
        "simulation",
        "action-conditioned-generation",
        "controllable-environment-generation"
      ],
      "scenarios": [
        "video-generation",
        "research-platforms"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "代表 Meta 在高保真视频世界建模与可编辑媒体生成上的系统化推进。",
      "editorial_summary_en": "A strong signal of Meta's push toward large-scale editable video world modeling.",
      "why_it_matters": "It expands world-model style media generation into a broader stack that combines video realism, instruction following, editing, and audio.",
      "related_project_slugs": [],
      "related_update_slugs": [
        "movie-gen-paper"
      ],
      "related_timeline_event_slugs": [
        "movie-gen-milestone"
      ],
      "featured": true
    },
    {
      "slug": "agent-planning-world-knowledge-model",
      "title_en": "Agent Planning with World Knowledge Model",
      "title_zh": "基于世界知识模型的智能体规划",
      "abstract_en": "This work introduces a world knowledge model to support agent planning by combining global prior knowledge with dynamic local task knowledge.",
      "abstract_zh": "该工作提出世界知识模型，通过结合全局先验知识与局部动态任务知识来辅助智能体规划。",
      "authors": [
        "Liang Zhang",
        "Zhongyu Wei",
        "Yujin Huang",
        "Yadong Xi"
      ],
      "affiliations": [
        "Multiple Institutions"
      ],
      "source_url": "https://openreview.net/forum?id=j6kJSS9O6I",
      "paper_venue": "NeurIPS",
      "publication_date": "2024-09-25",
      "year": 2024,
      "topics": [
        "world-models",
        "agentic-planning"
      ],
      "capabilities": [
        "planning",
        "long-horizon-reasoning",
        "prediction"
      ],
      "scenarios": [
        "agents",
        "research-platforms"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "是把世界模型思路明确迁移到语言智能体规划中的代表工作。",
      "editorial_summary_en": "A representative paper that ports world-model thinking into language-agent planning.",
      "why_it_matters": "It gives the site a clearer bridge from classical world models into modern agent planning systems.",
      "related_project_slugs": [],
      "related_update_slugs": [
        "world-knowledge-model-published"
      ],
      "related_timeline_event_slugs": [
        "world-knowledge-model-milestone"
      ],
      "featured": false
    },
    {
      "slug": "sima",
      "title_en": "SIMA: Scalable Instructable Multiworld Agent",
      "title_zh": "SIMA：可扩展可指令多世界智能体",
      "abstract_en": "An agent benchmark and system spanning multiple 3D game-like environments.",
      "abstract_zh": "跨多个 3D 类游戏环境的智能体系统与基准。",
      "authors": [
        "Google DeepMind"
      ],
      "affiliations": [
        "Google DeepMind"
      ],
      "source_url": "https://deepmind.google/discover/blog/sima-generalist-ai-agent-for-3d-virtual-environments/",
      "paper_venue": "DeepMind Blog",
      "publication_date": "2024-03-13",
      "year": 2024,
      "topics": [
        "world-models",
        "game-environment-world-models",
        "agentic-planning"
      ],
      "capabilities": [
        "planning",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "gaming",
        "agents"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "世界模型与通用虚拟环境智能体的交叉案例。",
      "editorial_summary_en": "A bridge between world models and generalist virtual agents.",
      "why_it_matters": "Shows why interactive environments matter for evaluating agent planning.",
      "related_project_slugs": [],
      "related_update_slugs": [
        "sima-announcement"
      ],
      "related_timeline_event_slugs": [
        "sima-milestone"
      ],
      "featured": false
    },
    {
      "slug": "genie-1",
      "title_en": "Genie: Generative Interactive Environments",
      "title_zh": "Genie：生成式交互环境",
      "abstract_en": "A precursor to more capable interactive world-model systems.",
      "abstract_zh": "更强交互式世界模型系统的前序工作。",
      "authors": [
        "Google DeepMind"
      ],
      "affiliations": [
        "Google DeepMind"
      ],
      "source_url": "https://arxiv.org/abs/2402.15391",
      "paper_venue": "arXiv",
      "publication_date": "2024-02-23",
      "year": 2024,
      "topics": [
        "world-models",
        "video-world-models",
        "game-environment-world-models"
      ],
      "capabilities": [
        "simulation",
        "controllable-environment-generation"
      ],
      "scenarios": [
        "gaming",
        "video-generation"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "为 Genie 2 铺路的关键一步。",
      "editorial_summary_en": "An important precursor to Genie 2.",
      "why_it_matters": "Useful to understand the evolution from static prediction to richer interaction.",
      "related_project_slugs": [
        "genie-2-project"
      ],
      "related_update_slugs": [
        "genie-1-paper"
      ],
      "related_timeline_event_slugs": [
        "genie-1-milestone"
      ],
      "featured": false
    },
    {
      "slug": "v-jepa",
      "title_en": "V-JEPA: Video Joint Embedding Predictive Architecture",
      "title_zh": "V-JEPA：视频联合嵌入预测架构",
      "abstract_en": "A self-supervised predictive architecture for learning from video without pixel-level generation.",
      "abstract_zh": "一种无需像素级生成、从视频中进行自监督预测学习的架构。",
      "authors": [
        "Meta"
      ],
      "affiliations": [
        "Meta AI"
      ],
      "source_url": "https://arxiv.org/abs/2401.09417",
      "paper_venue": "arXiv",
      "publication_date": "2024-02-13",
      "year": 2024,
      "project_url": "https://ai.meta.com/blog/v-jepa-yann-lecun-ai-model-video-joint-embedding-predictive-architecture/",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "capabilities": [
        "prediction",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "video-generation",
        "research-platforms"
      ],
      "importance_level": "medium",
      "editorial_summary_zh": "代表了视频世界模型中预测式而非重建式的路线。",
      "editorial_summary_en": "Represents predictive rather than reconstructive video modeling.",
      "why_it_matters": "Important for understanding alternatives to generative video world models.",
      "related_project_slugs": [
        "v-jepa"
      ],
      "related_update_slugs": [
        "v-jepa-release"
      ],
      "related_timeline_event_slugs": [
        "v-jepa-milestone"
      ],
      "featured": true
    },
    {
      "slug": "gaia-1",
      "title_en": "GAIA-1: A Generative World Model for Autonomous Driving",
      "title_zh": "GAIA-1：面向自动驾驶的生成式世界模型",
      "abstract_en": "Wayve presents a generative world model for driving scenes and future rollout.",
      "abstract_zh": "Wayve 提出面向驾驶场景和未来展开的生成式世界模型。",
      "authors": [
        "Wayve"
      ],
      "affiliations": [
        "Wayve"
      ],
      "source_url": "https://wayve.ai/thinking/gaia-1/",
      "paper_venue": "Wayve Blog",
      "publication_date": "2023-11-09",
      "year": 2023,
      "project_url": "https://wayve.ai/thinking/gaia-1/",
      "topics": [
        "world-models",
        "driving-world-models"
      ],
      "capabilities": [
        "prediction",
        "simulation",
        "action-conditioned-generation"
      ],
      "scenarios": [
        "autonomous-driving"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "自动驾驶里将世界模型概念产品化的重要里程碑。",
      "editorial_summary_en": "A major step in world-model narratives for driving.",
      "why_it_matters": "Shows how generative scene modeling can support autonomous-driving evaluation and forecasting.",
      "related_project_slugs": [
        "gaia-1"
      ],
      "related_update_slugs": [
        "gaia-1-blog"
      ],
      "related_timeline_event_slugs": [
        "gaia-1-milestone"
      ],
      "featured": true
    },
    {
      "slug": "dreamerv3",
      "title_en": "Mastering Diverse Domains through World Models",
      "title_zh": "通过世界模型掌握多样领域",
      "abstract_en": "DreamerV3 shows general reinforcement learning from learned latent world models.",
      "abstract_zh": "DreamerV3 展示了基于学习到的潜在世界模型的通用强化学习能力。",
      "authors": [
        "Danijar Hafner",
        "Google DeepMind"
      ],
      "affiliations": [
        "Google DeepMind"
      ],
      "source_url": "https://arxiv.org/abs/2301.04104",
      "paper_venue": "arXiv",
      "publication_date": "2023-07-30",
      "year": 2023,
      "code_url": "https://github.com/danijar/dreamerv3",
      "project_url": "https://danijar.com/project/dreamerv3/",
      "topics": [
        "world-models",
        "game-environment-world-models",
        "agentic-planning"
      ],
      "capabilities": [
        "prediction",
        "planning",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "gaming",
        "agents",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "潜在世界模型用于决策与控制的经典代表。",
      "editorial_summary_en": "A canonical learned-world-model agent paper.",
      "why_it_matters": "It demonstrates that compact latent world models can support strong generalist control.",
      "related_project_slugs": [
        "dreamerv3"
      ],
      "related_update_slugs": [
        "dreamerv3-paper"
      ],
      "related_timeline_event_slugs": [
        "dreamerv3-milestone"
      ],
      "featured": true
    },
    {
      "slug": "world-models-2018",
      "title_en": "World Models",
      "title_zh": "世界模型",
      "abstract_en": "An early paper demonstrating compact environment models for control.",
      "abstract_zh": "早期展示如何用紧凑环境模型服务控制任务的代表论文。",
      "authors": [
        "David Ha",
        "Jürgen Schmidhuber"
      ],
      "affiliations": [
        "Independent"
      ],
      "source_url": "https://arxiv.org/abs/1803.10122",
      "paper_venue": "arXiv",
      "publication_date": "2018-03-27",
      "year": 2018,
      "topics": [
        "world-models",
        "game-environment-world-models"
      ],
      "capabilities": [
        "prediction",
        "planning"
      ],
      "scenarios": [
        "gaming",
        "research-platforms"
      ],
      "importance_level": "high",
      "editorial_summary_zh": "世界模型概念进入主流讨论的起点之一。",
      "editorial_summary_en": "One of the foundational papers that popularized the term.",
      "why_it_matters": "It gave the field a durable conceptual frame and a memorable name.",
      "related_project_slugs": [],
      "related_update_slugs": [
        "world-models-retrospective"
      ],
      "related_timeline_event_slugs": [
        "world-models-paper"
      ],
      "featured": false
    }
  ],
  "projects": [
    {
      "slug": "sora-2-project",
      "name": "Sora 2",
      "description_en": "OpenAI's next-generation video and audio generation system with stronger physical accuracy, synchronized sound, and improved controllability.",
      "description_zh": "OpenAI 新一代视频与音频生成系统，强调更强的物理一致性、同步声音和可控性。",
      "type": "product",
      "organization": "OpenAI",
      "source_url": "https://openai.com/index/sora-2/",
      "demo_url": "https://openai.com/index/sora-2-system-card/",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "capabilities": [
        "prediction",
        "simulation",
        "action-conditioned-generation"
      ],
      "scenarios": [
        "video-generation",
        "research-platforms"
      ],
      "maturity": "active",
      "related_paper_slugs": [],
      "related_update_slugs": [
        "sora-2-launch"
      ],
      "editorial_summary_zh": "把视频世界模型从研究展示进一步推向产品化和更强物理模拟表达。",
      "editorial_summary_en": "Shows video world models moving closer to product deployment with stronger simulation fidelity.",
      "release_date": "2025-09-30",
      "featured": true
    },
    {
      "slug": "gaia-2-project",
      "name": "GAIA-2",
      "description_en": "Wayve's second-generation controllable driving world model for synthetic scenario generation and autonomy evaluation.",
      "description_zh": "Wayve 第二代可控驾驶世界模型，用于合成场景生成与自动驾驶评测。",
      "type": "framework",
      "organization": "Wayve",
      "source_url": "https://wayve.ai/press/wayve-unveils-gaia2/",
      "demo_url": "https://wayve.ai/thinking/gaia-2/",
      "topics": [
        "world-models",
        "driving-world-models"
      ],
      "capabilities": [
        "prediction",
        "simulation",
        "controllable-environment-generation"
      ],
      "scenarios": [
        "autonomous-driving",
        "research-platforms"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "gaia-2"
      ],
      "related_update_slugs": [
        "gaia-2-release"
      ],
      "editorial_summary_zh": "把世界模型正式推向自动驾驶训练、验证和安全测试链路。",
      "editorial_summary_en": "Pushes driving world models into the training and evaluation stack for autonomy.",
      "release_date": "2025-03-26",
      "featured": true
    },
    {
      "slug": "groot-n1-project",
      "name": "NVIDIA Isaac GR00T N1",
      "description_en": "An open humanoid robot foundation model designed to accelerate skill learning, transfer, and deployment for physical AI systems.",
      "description_zh": "面向 Physical AI 的开放人形机器人基础模型，用于加速技能学习、迁移与部署。",
      "type": "framework",
      "organization": "NVIDIA",
      "source_url": "https://research.nvidia.com/publication/2025-03_nvidia-isaac-gr00t-n1-open-foundation-model-humanoid-robots",
      "demo_url": "https://developer.nvidia.com/blog/accelerate-generalist-humanoid-robot-development-with-nvidia-isaac-gr00t-n1/",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "capabilities": [
        "planning",
        "simulation",
        "prediction"
      ],
      "scenarios": [
        "robotics",
        "research-platforms"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "groot-n1"
      ],
      "related_update_slugs": [
        "groot-n1-launch"
      ],
      "editorial_summary_zh": "把人形机器人训练、推理与仿真平台结合成了清晰的产品路线。",
      "editorial_summary_en": "Connects humanoid robot training, reasoning, and simulation into a coherent platform play.",
      "release_date": "2025-03-17",
      "featured": true
    },
    {
      "slug": "gemini-robotics-project",
      "name": "Gemini Robotics",
      "description_en": "Google DeepMind's embodied robotics model family spanning general robot control and embodied reasoning.",
      "description_zh": "Google DeepMind 的具身机器人模型系列，覆盖通用机器人控制与具身推理。",
      "type": "product",
      "organization": "Google DeepMind",
      "source_url": "https://deepmind.google/technologies/gemini-robotics/",
      "demo_url": "https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models",
        "agentic-planning"
      ],
      "capabilities": [
        "planning",
        "prediction",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "robotics",
        "agents",
        "research-platforms"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "gemini-robotics"
      ],
      "related_update_slugs": [
        "gemini-robotics-launch"
      ],
      "editorial_summary_zh": "把具身推理和物理执行统一到 Gemini 机器人产品线里。",
      "editorial_summary_en": "Unifies embodied reasoning and physical execution in the Gemini robotics line.",
      "release_date": "2025-03-12",
      "featured": true
    },
    {
      "slug": "cosmos-platform",
      "name": "NVIDIA Cosmos",
      "description_en": "World foundation model platform for physical AI and robotics.",
      "description_zh": "面向 Physical AI 与机器人的世界基础模型平台。",
      "type": "product",
      "organization": "NVIDIA",
      "source_url": "https://www.nvidia.com/en-us/ai/cosmos/",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models",
        "driving-world-models"
      ],
      "capabilities": [
        "simulation",
        "prediction",
        "planning"
      ],
      "scenarios": [
        "robotics",
        "autonomous-driving",
        "research-platforms"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "cosmos-world-foundation-models"
      ],
      "related_update_slugs": [
        "cosmos-platform-launch"
      ],
      "editorial_summary_zh": "把世界模型明确推向机器人和物理 AI 平台层。",
      "editorial_summary_en": "Pushes world models toward a physical-AI platform role.",
      "release_date": "2025-01-06",
      "featured": true
    },
    {
      "slug": "genie-2-project",
      "name": "Genie 2",
      "description_en": "Interactive environment generation system from Google DeepMind.",
      "description_zh": "Google DeepMind 推出的可交互环境生成系统。",
      "type": "demo",
      "organization": "Google DeepMind",
      "source_url": "https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/",
      "demo_url": "https://deepmind.google/",
      "topics": [
        "world-models",
        "video-world-models",
        "game-environment-world-models"
      ],
      "capabilities": [
        "simulation",
        "controllable-environment-generation"
      ],
      "scenarios": [
        "gaming",
        "research-platforms",
        "video-generation"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "genie-2"
      ],
      "related_update_slugs": [
        "genie-2-release"
      ],
      "editorial_summary_zh": "展示了大规模交互式世界生成的产品化形态。",
      "editorial_summary_en": "A flagship demo of interactive world generation.",
      "release_date": "2024-12-04",
      "featured": true
    },
    {
      "slug": "v-jepa",
      "name": "V-JEPA",
      "description_en": "Self-supervised video prediction framework from Meta.",
      "description_zh": "Meta 推出的自监督视频预测框架。",
      "type": "framework",
      "organization": "Meta",
      "source_url": "https://ai.meta.com/blog/v-jepa-yann-lecun-ai-model-video-joint-embedding-predictive-architecture/",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "capabilities": [
        "prediction",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "video-generation",
        "research-platforms"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "v-jepa"
      ],
      "related_update_slugs": [
        "v-jepa-release"
      ],
      "editorial_summary_zh": "提供了视频世界模型的一条自监督路线。",
      "editorial_summary_en": "A key self-supervised route into video world models.",
      "release_date": "2024-02-13",
      "featured": false
    },
    {
      "slug": "gaia-1",
      "name": "GAIA-1",
      "description_en": "Generative world model for autonomous driving from Wayve.",
      "description_zh": "Wayve 发布的自动驾驶生成式世界模型。",
      "type": "demo",
      "organization": "Wayve",
      "source_url": "https://wayve.ai/thinking/gaia-1/",
      "topics": [
        "world-models",
        "driving-world-models"
      ],
      "capabilities": [
        "prediction",
        "simulation",
        "action-conditioned-generation"
      ],
      "scenarios": [
        "autonomous-driving"
      ],
      "maturity": "active",
      "related_paper_slugs": [
        "gaia-1"
      ],
      "related_update_slugs": [
        "gaia-1-blog"
      ],
      "editorial_summary_zh": "是自动驾驶领域世界模型化叙事的重要案例。",
      "editorial_summary_en": "A prominent world-model framing for autonomous driving.",
      "release_date": "2023-11-09",
      "featured": true
    },
    {
      "slug": "dreamerv3",
      "name": "DreamerV3",
      "description_en": "General reinforcement learning agent built on latent world models.",
      "description_zh": "建立在潜在世界模型上的通用强化学习智能体。",
      "type": "open-source",
      "organization": "Google DeepMind",
      "source_url": "https://danijar.com/project/dreamerv3/",
      "repo_url": "https://github.com/danijar/dreamerv3",
      "topics": [
        "world-models",
        "game-environment-world-models",
        "agentic-planning"
      ],
      "capabilities": [
        "prediction",
        "planning",
        "long-horizon-reasoning"
      ],
      "scenarios": [
        "gaming",
        "agents",
        "research-platforms"
      ],
      "maturity": "established",
      "related_paper_slugs": [
        "dreamerv3"
      ],
      "related_update_slugs": [
        "dreamerv3-paper"
      ],
      "editorial_summary_zh": "是潜在世界模型驱动决策的代表性系统。",
      "editorial_summary_en": "A canonical latent world-model agent.",
      "release_date": "2023-07-01",
      "featured": true
    }
  ],
  "updates": [
    {
      "slug": "sora-2-launch",
      "title_en": "OpenAI launches Sora 2",
      "title_zh": "OpenAI 发布 Sora 2",
      "date": "2025-09-30",
      "source_name": "OpenAI",
      "source_url": "https://openai.com/index/sora-2/",
      "update_type": "product-release",
      "summary_en": "Sora 2 adds stronger physical accuracy, synchronized dialogue and sound, and a broader product deployment path.",
      "summary_zh": "Sora 2 强化了物理一致性、同步对白与音效，并开始走向更完整的产品部署。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "related_paper_slugs": [],
      "related_project_slugs": [
        "sora-2-project"
      ],
      "related_company_names": [
        "OpenAI"
      ],
      "published": true
    },
    {
      "slug": "embodied-intelligence-survey-published",
      "title_en": "Survey maps embodied intelligence through simulators and world models",
      "title_zh": "综述梳理模拟器与世界模型驱动的具身智能",
      "date": "2025-07-01",
      "source_name": "arXiv",
      "source_url": "https://arxiv.org/abs/2507.00917",
      "update_type": "survey",
      "summary_en": "A new survey connects physical simulators, internal world models, robot learning, and sim-to-real deployment.",
      "summary_zh": "一篇新综述连接了物理模拟器、内部世界模型、机器人学习与 sim-to-real 部署。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "related_paper_slugs": [
        "embodied-intelligence-simulators-world-models-survey"
      ],
      "related_project_slugs": [],
      "related_company_names": [],
      "published": true
    },
    {
      "slug": "iclr-2025-workshop",
      "title_en": "ICLR 2025 hosts a dedicated world-models workshop",
      "title_zh": "ICLR 2025 设立世界模型专题研讨会",
      "date": "2025-04-20",
      "source_name": "OpenReview",
      "source_url": "https://openreview.net/group?id=ICLR.cc/2025/Workshop/World_Models",
      "update_type": "survey",
      "summary_en": "A dedicated workshop signals the field’s breadth and momentum.",
      "summary_zh": "专题研讨会说明该方向已形成更稳定的研究共同体。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "embodied-world-models",
        "agentic-planning"
      ],
      "related_paper_slugs": [
        "iclr-2025-world-models-workshop"
      ],
      "related_project_slugs": [],
      "related_company_names": [
        "ICLR"
      ],
      "published": true
    },
    {
      "slug": "gaia-2-release",
      "title_en": "Wayve launches GAIA-2 for controllable driving simulation",
      "title_zh": "Wayve 发布 GAIA-2 可控驾驶仿真世界模型",
      "date": "2025-03-26",
      "source_name": "Wayve",
      "source_url": "https://wayve.ai/press/wayve-unveils-gaia2/",
      "update_type": "model-release",
      "summary_en": "GAIA-2 adds richer and more controllable synthetic driving scenarios for training, evaluation, and safety testing.",
      "summary_zh": "GAIA-2 提供更丰富、可控的合成驾驶场景，用于训练、评测与安全测试。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "driving-world-models"
      ],
      "related_paper_slugs": [
        "gaia-2"
      ],
      "related_project_slugs": [
        "gaia-2-project"
      ],
      "related_company_names": [
        "Wayve"
      ],
      "published": true
    },
    {
      "slug": "groot-n1-launch",
      "title_en": "NVIDIA launches GR00T N1 for humanoid robots",
      "title_zh": "NVIDIA 发布面向人形机器人的 GR00T N1",
      "date": "2025-03-17",
      "source_name": "NVIDIA",
      "source_url": "https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Announces-Isaac-GR00T-N1--the-Worlds-First-Open-Humanoid-Robot-Foundation-Model--and-Simulation-Frameworks-to-Speed-Robot-Development/default.aspx",
      "update_type": "product-release",
      "summary_en": "GR00T N1 brings an open humanoid robot foundation model and simulation tooling into NVIDIA's physical AI stack.",
      "summary_zh": "GR00T N1 将开放人形机器人基础模型与仿真工具带入 NVIDIA 的 Physical AI 体系。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "related_paper_slugs": [
        "groot-n1"
      ],
      "related_project_slugs": [
        "groot-n1-project"
      ],
      "related_company_names": [
        "NVIDIA"
      ],
      "published": true
    },
    {
      "slug": "gemini-robotics-launch",
      "title_en": "Google DeepMind launches Gemini Robotics",
      "title_zh": "Google DeepMind 发布 Gemini Robotics",
      "date": "2025-03-12",
      "source_name": "Google DeepMind",
      "source_url": "https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/",
      "update_type": "product-release",
      "summary_en": "Gemini Robotics and Gemini Robotics-ER extend Gemini into embodied reasoning and robot control.",
      "summary_zh": "Gemini Robotics 与 Gemini Robotics-ER 将 Gemini 扩展到具身推理与机器人控制。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models",
        "agentic-planning"
      ],
      "related_paper_slugs": [
        "gemini-robotics"
      ],
      "related_project_slugs": [
        "gemini-robotics-project"
      ],
      "related_company_names": [
        "Google DeepMind"
      ],
      "published": true
    },
    {
      "slug": "embodied-survey-published",
      "title_en": "Survey maps embodied world-model methods",
      "title_zh": "综述梳理具身世界模型方法版图",
      "date": "2025-01-15",
      "source_name": "arXiv",
      "source_url": "https://arxiv.org/abs/2501.00001",
      "update_type": "survey",
      "summary_en": "A survey summarizes the design space for embodied and robotic world models.",
      "summary_zh": "一篇综述总结了具身与机器人世界模型的方法空间。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models"
      ],
      "related_paper_slugs": [
        "embodied-world-model-survey"
      ],
      "related_project_slugs": [
        "cosmos-platform"
      ],
      "related_company_names": [],
      "published": true
    },
    {
      "slug": "cosmos-platform-launch",
      "title_en": "NVIDIA launches Cosmos for physical AI",
      "title_zh": "NVIDIA 推出 Cosmos 面向 Physical AI",
      "date": "2025-01-06",
      "source_name": "NVIDIA",
      "source_url": "https://www.nvidia.com/en-us/ai/cosmos/",
      "update_type": "product-release",
      "summary_en": "Cosmos packages world-foundation-model ideas into a platform for robotics and autonomy.",
      "summary_zh": "Cosmos 将世界基础模型包装成机器人与自治系统的平台。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "embodied-world-models",
        "robotics-world-models",
        "driving-world-models"
      ],
      "related_paper_slugs": [
        "cosmos-world-foundation-models"
      ],
      "related_project_slugs": [
        "cosmos-platform"
      ],
      "related_company_names": [
        "NVIDIA"
      ],
      "published": true
    },
    {
      "slug": "genie-2-release",
      "title_en": "DeepMind unveils Genie 2",
      "title_zh": "DeepMind 发布 Genie 2",
      "date": "2024-12-04",
      "source_name": "Google DeepMind",
      "source_url": "https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/",
      "update_type": "model-release",
      "summary_en": "Genie 2 presents a more capable interactive environment generation system.",
      "summary_zh": "Genie 2 展示了更强的可交互环境生成能力。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "video-world-models",
        "game-environment-world-models"
      ],
      "related_paper_slugs": [
        "genie-2"
      ],
      "related_project_slugs": [
        "genie-2-project"
      ],
      "related_company_names": [
        "Google DeepMind"
      ],
      "published": true
    },
    {
      "slug": "movie-gen-paper",
      "title_en": "Meta publishes Movie Gen",
      "title_zh": "Meta 发布 Movie Gen",
      "date": "2024-10-17",
      "source_name": "arXiv",
      "source_url": "https://arxiv.org/abs/2410.13720",
      "update_type": "paper",
      "summary_en": "Movie Gen introduces a broader media foundation model stack for text-to-video, editing, personalization, and synchronized audio.",
      "summary_zh": "Movie Gen 发布了一套更完整的媒体基础模型体系，覆盖文生视频、编辑、个性化和同步音频。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "related_paper_slugs": [
        "movie-gen"
      ],
      "related_project_slugs": [],
      "related_company_names": [
        "Meta"
      ],
      "published": true
    },
    {
      "slug": "world-knowledge-model-published",
      "title_en": "World knowledge model paper links world models to agent planning",
      "title_zh": "世界知识模型论文把世界模型思路接到智能体规划上",
      "date": "2024-09-25",
      "source_name": "OpenReview",
      "source_url": "https://openreview.net/forum?id=j6kJSS9O6I",
      "update_type": "paper",
      "summary_en": "The paper proposes a world knowledge model to improve agent planning with global and local task knowledge.",
      "summary_zh": "该论文提出世界知识模型，用全局与局部任务知识提升智能体规划。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "agentic-planning"
      ],
      "related_paper_slugs": [
        "agent-planning-world-knowledge-model"
      ],
      "related_project_slugs": [],
      "related_company_names": [],
      "published": true
    },
    {
      "slug": "world-models-retrospective",
      "title_en": "The 2018 World Models paper remains the field’s conceptual anchor",
      "title_zh": "2018 年 World Models 论文仍是该领域的概念锚点",
      "date": "2024-06-01",
      "source_name": "Editorial",
      "source_url": "https://arxiv.org/abs/1803.10122",
      "update_type": "survey",
      "summary_en": "Even newer systems still inherit framing from the original World Models paper.",
      "summary_zh": "即便新系统不断出现，最初的 World Models 论文仍在定义讨论框架。",
      "importance_level": "low",
      "topics": [
        "world-models",
        "game-environment-world-models"
      ],
      "related_paper_slugs": [
        "world-models-2018"
      ],
      "related_project_slugs": [],
      "related_company_names": [],
      "published": true
    },
    {
      "slug": "sima-announcement",
      "title_en": "DeepMind introduces SIMA for virtual environments",
      "title_zh": "DeepMind 发布面向虚拟环境的 SIMA",
      "date": "2024-03-13",
      "source_name": "Google DeepMind",
      "source_url": "https://deepmind.google/discover/blog/sima-generalist-ai-agent-for-3d-virtual-environments/",
      "update_type": "product-release",
      "summary_en": "SIMA highlights interactive environments as a proving ground for agent planning.",
      "summary_zh": "SIMA 强调交互式环境是智能体规划的重要试验场。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "game-environment-world-models",
        "agentic-planning"
      ],
      "related_paper_slugs": [
        "sima"
      ],
      "related_project_slugs": [],
      "related_company_names": [
        "Google DeepMind"
      ],
      "published": true
    },
    {
      "slug": "genie-1-paper",
      "title_en": "Genie pushes toward generative interactive environments",
      "title_zh": "Genie 推进到生成式交互环境",
      "date": "2024-02-23",
      "source_name": "arXiv",
      "source_url": "https://arxiv.org/abs/2402.15391",
      "update_type": "paper",
      "summary_en": "Genie becomes an important precursor to larger interactive world models.",
      "summary_zh": "Genie 成为更大规模交互式世界模型的重要前序工作。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "video-world-models",
        "game-environment-world-models"
      ],
      "related_paper_slugs": [
        "genie-1"
      ],
      "related_project_slugs": [
        "genie-2-project"
      ],
      "related_company_names": [
        "Google DeepMind"
      ],
      "published": true
    },
    {
      "slug": "v-jepa-release",
      "title_en": "Meta releases V-JEPA",
      "title_zh": "Meta 发布 V-JEPA",
      "date": "2024-02-13",
      "source_name": "Meta",
      "source_url": "https://ai.meta.com/blog/v-jepa-yann-lecun-ai-model-video-joint-embedding-predictive-architecture/",
      "update_type": "model-release",
      "summary_en": "Meta proposes a predictive route for learning from video without pixel generation.",
      "summary_zh": "Meta 提出了一条不依赖像素生成的视频预测路线。",
      "importance_level": "medium",
      "topics": [
        "world-models",
        "video-world-models"
      ],
      "related_paper_slugs": [
        "v-jepa"
      ],
      "related_project_slugs": [
        "v-jepa"
      ],
      "related_company_names": [
        "Meta"
      ],
      "published": true
    },
    {
      "slug": "gaia-1-blog",
      "title_en": "Wayve frames autonomous driving with GAIA-1",
      "title_zh": "Wayve 用 GAIA-1 重塑自动驾驶叙事",
      "date": "2023-11-09",
      "source_name": "Wayve",
      "source_url": "https://wayve.ai/thinking/gaia-1/",
      "update_type": "company-blog",
      "summary_en": "Wayve introduces GAIA-1 as a generative world model for driving scenes.",
      "summary_zh": "Wayve 将 GAIA-1 定义为自动驾驶场景的生成式世界模型。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "driving-world-models"
      ],
      "related_paper_slugs": [
        "gaia-1"
      ],
      "related_project_slugs": [
        "gaia-1"
      ],
      "related_company_names": [
        "Wayve"
      ],
      "published": true
    },
    {
      "slug": "dreamerv3-paper",
      "title_en": "DreamerV3 becomes a reference point for latent world-model agents",
      "title_zh": "DreamerV3 成为潜在世界模型智能体的重要参照",
      "date": "2023-07-30",
      "source_name": "arXiv",
      "source_url": "https://arxiv.org/abs/2301.04104",
      "update_type": "paper",
      "summary_en": "DreamerV3 demonstrates strong generality across domains using latent world models.",
      "summary_zh": "DreamerV3 展示了潜在世界模型在多领域上的通用性。",
      "importance_level": "high",
      "topics": [
        "world-models",
        "agentic-planning",
        "game-environment-world-models"
      ],
      "related_paper_slugs": [
        "dreamerv3"
      ],
      "related_project_slugs": [
        "dreamerv3"
      ],
      "related_company_names": [
        "Google DeepMind"
      ],
      "published": true
    }
  ],
  "timeline": [
    {
      "slug": "sora-2-milestone",
      "title_en": "Sora 2 moves video world models closer to deployment",
      "title_zh": "Sora 2 让视频世界模型更接近产品部署",
      "date": "2025-09-30",
      "description_en": "OpenAI launches Sora 2 with stronger physical realism, synchronized audio, and a clearer product rollout path.",
      "description_zh": "OpenAI 推出 Sora 2，强调更强物理真实感、同步音频，以及更清晰的产品化落地路径。",
      "event_type": "company-launch",
      "related_paper_slugs": [],
      "related_project_slugs": [
        "sora-2-project"
      ],
      "related_org_names": [
        "OpenAI"
      ],
      "why_it_matters": "It shows that world-model-like video systems are becoming product surfaces rather than only research demos.",
      "featured": true
    },
    {
      "slug": "embodied-intelligence-survey-milestone",
      "title_en": "Survey synthesizes simulators and internal world models for embodied AI",
      "title_zh": "综述整合具身 AI 中的模拟器与内部世界模型",
      "date": "2025-07-01",
      "description_en": "A survey organizes how simulation platforms and world models jointly shape embodied intelligence research.",
      "description_zh": "一篇综述系统整理了仿真平台与世界模型如何共同塑造具身智能研究。",
      "event_type": "survey",
      "related_paper_slugs": [
        "embodied-intelligence-simulators-world-models-survey"
      ],
      "related_project_slugs": [],
      "related_org_names": [],
      "why_it_matters": "It gives the field a more mature map of embodied world-model research and deployment challenges.",
      "featured": false
    },
    {
      "slug": "iclr-workshop",
      "title_en": "World-models workshop appears at ICLR 2025",
      "title_zh": "ICLR 2025 出现世界模型专题研讨会",
      "date": "2025-04-20",
      "description_en": "A workshop reflects community-level consolidation around the topic.",
      "description_zh": "专题研讨会反映出社区层面对该主题的收敛。",
      "event_type": "milestone",
      "related_paper_slugs": [
        "iclr-2025-world-models-workshop"
      ],
      "related_project_slugs": [],
      "related_org_names": [
        "ICLR"
      ],
      "why_it_matters": "Good evidence that the category is coherent enough to sustain a dedicated information site.",
      "featured": false
    },
    {
      "slug": "gaia-2-milestone",
      "title_en": "GAIA-2 expands controllable driving-world-models",
      "title_zh": "GAIA-2 推进可控驾驶世界模型",
      "date": "2025-03-26",
      "description_en": "Wayve positions GAIA-2 as a more controllable and scalable driving world model for synthetic data generation and evaluation.",
      "description_zh": "Wayve 将 GAIA-2 定位为更可控、可扩展的驾驶世界模型，用于合成数据生成与评测。",
      "event_type": "model-release",
      "related_paper_slugs": [
        "gaia-2"
      ],
      "related_project_slugs": [
        "gaia-2-project"
      ],
      "related_org_names": [
        "Wayve"
      ],
      "why_it_matters": "Driving world models are shifting from demos toward infrastructure for data generation and validation.",
      "featured": true
    },
    {
      "slug": "groot-n1-milestone",
      "title_en": "GR00T N1 brings world-model infrastructure into humanoid robotics",
      "title_zh": "GR00T N1 把世界模型基础设施推进到人形机器人",
      "date": "2025-03-17",
      "description_en": "NVIDIA packages open humanoid robot modeling, simulation, and transfer tooling into the GR00T N1 release.",
      "description_zh": "NVIDIA 在 GR00T N1 发布中把开放人形机器人建模、仿真和迁移工具打包成体系。",
      "event_type": "company-launch",
      "related_paper_slugs": [
        "groot-n1"
      ],
      "related_project_slugs": [
        "groot-n1-project"
      ],
      "related_org_names": [
        "NVIDIA"
      ],
      "why_it_matters": "It marks a stronger convergence between world-model infrastructure and deployable humanoid robot systems.",
      "featured": true
    },
    {
      "slug": "gemini-robotics-milestone",
      "title_en": "Gemini Robotics expands world-model ideas into embodied reasoning",
      "title_zh": "Gemini Robotics 把世界模型思路扩展到具身推理",
      "date": "2025-03-12",
      "description_en": "Google DeepMind extends Gemini into embodied reasoning and robot action with Gemini Robotics and Gemini Robotics-ER.",
      "description_zh": "Google DeepMind 通过 Gemini Robotics 与 Gemini Robotics-ER 把 Gemini 扩展到具身推理与机器人动作。",
      "event_type": "company-launch",
      "related_paper_slugs": [
        "gemini-robotics"
      ],
      "related_project_slugs": [
        "gemini-robotics-project"
      ],
      "related_org_names": [
        "Google DeepMind"
      ],
      "why_it_matters": "It reframes physical agents as world-understanding and planning systems, not just action policies.",
      "featured": true
    },
    {
      "slug": "embodied-survey",
      "title_en": "Embodied world-model survey consolidates the field",
      "title_zh": "具身世界模型综述让该方向进一步收敛",
      "date": "2025-01-15",
      "description_en": "A survey helps new readers see the common structure across embodied world-model work.",
      "description_zh": "综述帮助新读者看到具身世界模型工作的共通结构。",
      "event_type": "survey",
      "related_paper_slugs": [
        "embodied-world-model-survey"
      ],
      "related_project_slugs": [
        "cosmos-platform"
      ],
      "related_org_names": [
        "Academic"
      ],
      "why_it_matters": "A sign that the embodied branch has become large enough to need structured synthesis.",
      "featured": false
    },
    {
      "slug": "cosmos-launch",
      "title_en": "Cosmos frames world models as physical-AI infrastructure",
      "title_zh": "Cosmos 将世界模型定位为 Physical AI 基础设施",
      "date": "2025-01-06",
      "description_en": "NVIDIA packages world models as a platform layer for robots and autonomy stacks.",
      "description_zh": "NVIDIA 将世界模型包装成机器人与自治系统的平台层。",
      "event_type": "company-launch",
      "related_paper_slugs": [
        "cosmos-world-foundation-models"
      ],
      "related_project_slugs": [
        "cosmos-platform"
      ],
      "related_org_names": [
        "NVIDIA"
      ],
      "why_it_matters": "Signals an infrastructure phase for the field.",
      "featured": true
    },
    {
      "slug": "genie-2-milestone",
      "title_en": "Genie 2 makes world models more interactive",
      "title_zh": "Genie 2 让世界模型更接近可交互系统",
      "date": "2024-12-04",
      "description_en": "Genie 2 moves world models from research artifact toward practical interactive environment generation.",
      "description_zh": "Genie 2 让世界模型从研究原型更接近实用的交互环境生成系统。",
      "event_type": "model-release",
      "related_paper_slugs": [
        "genie-2"
      ],
      "related_project_slugs": [
        "genie-2-project"
      ],
      "related_org_names": [
        "Google DeepMind"
      ],
      "why_it_matters": "A major step toward world models as interfaces, not just predictors.",
      "featured": true
    },
    {
      "slug": "movie-gen-milestone",
      "title_en": "Movie Gen raises the bar for media world models",
      "title_zh": "Movie Gen 抬高媒体世界模型能力上限",
      "date": "2024-10-17",
      "description_en": "Meta releases Movie Gen, showing stronger video generation, editing, personalization, and synchronized audio in a unified stack.",
      "description_zh": "Meta 发布 Movie Gen，在统一体系中展示了更强的视频生成、编辑、个性化与同步音频能力。",
      "event_type": "paper",
      "related_paper_slugs": [
        "movie-gen"
      ],
      "related_project_slugs": [],
      "related_org_names": [
        "Meta"
      ],
      "why_it_matters": "It broadens the scope of world models from prediction and simulation to richer end-user media systems.",
      "featured": false
    },
    {
      "slug": "world-knowledge-model-milestone",
      "title_en": "World-model reasoning crosses into language-agent planning",
      "title_zh": "世界模型推理跨入语言智能体规划",
      "date": "2024-09-25",
      "description_en": "Agent Planning with World Knowledge Model applies world-model-style reasoning to agent planning with global and local knowledge.",
      "description_zh": "《Agent Planning with World Knowledge Model》把世界模型式推理应用到结合全局与局部知识的智能体规划中。",
      "event_type": "paper",
      "related_paper_slugs": [
        "agent-planning-world-knowledge-model"
      ],
      "related_project_slugs": [],
      "related_org_names": [],
      "why_it_matters": "It helps connect the world-model tradition with the modern agentic-planning wave.",
      "featured": false
    },
    {
      "slug": "genie-1-milestone",
      "title_en": "Genie previews generative interactive environments",
      "title_zh": "Genie 预示生成式交互环境方向",
      "date": "2024-02-23",
      "description_en": "Genie shows the transition from prediction toward generated interaction.",
      "description_zh": "Genie 展示了从预测走向生成式交互的过渡。",
      "event_type": "milestone",
      "related_paper_slugs": [
        "genie-1"
      ],
      "related_project_slugs": [
        "genie-2-project"
      ],
      "related_org_names": [
        "Google DeepMind"
      ],
      "why_it_matters": "Sets up the leap to more capable environment world models.",
      "featured": false
    },
    {
      "slug": "v-jepa-milestone",
      "title_en": "V-JEPA strengthens the predictive video route",
      "title_zh": "V-JEPA 强化了预测式视频路线",
      "date": "2024-02-13",
      "description_en": "Meta shows that video prediction can avoid direct pixel reconstruction.",
      "description_zh": "Meta 展示了视频预测可以不依赖直接像素重建。",
      "event_type": "paper",
      "related_paper_slugs": [
        "v-jepa"
      ],
      "related_project_slugs": [
        "v-jepa"
      ],
      "related_org_names": [
        "Meta"
      ],
      "why_it_matters": "Important for how the field thinks about efficient world-model representations.",
      "featured": false
    },
    {
      "slug": "gaia-1-milestone",
      "title_en": "GAIA-1 brings world models into autonomous driving narratives",
      "title_zh": "GAIA-1 将世界模型引入自动驾驶主叙事",
      "date": "2023-11-09",
      "description_en": "Wayve shows how world-model framing can support driving simulation and forecasting.",
      "description_zh": "Wayve 展示了世界模型叙事如何服务自动驾驶仿真与预测。",
      "event_type": "company-launch",
      "related_paper_slugs": [
        "gaia-1"
      ],
      "related_project_slugs": [
        "gaia-1"
      ],
      "related_org_names": [
        "Wayve"
      ],
      "why_it_matters": "Marks a major vertical application beyond games.",
      "featured": true
    },
    {
      "slug": "dreamerv3-milestone",
      "title_en": "DreamerV3 proves latent world models remain competitive",
      "title_zh": "DreamerV3 证明潜在世界模型路线依然强劲",
      "date": "2023-07-30",
      "description_en": "DreamerV3 becomes a reference implementation for model-based RL at scale.",
      "description_zh": "DreamerV3 成为大规模模型驱动强化学习的重要参照实现。",
      "event_type": "milestone",
      "related_paper_slugs": [
        "dreamerv3"
      ],
      "related_project_slugs": [
        "dreamerv3"
      ],
      "related_org_names": [
        "Google DeepMind"
      ],
      "why_it_matters": "It keeps the model-based control tradition relevant in the era of foundation models.",
      "featured": true
    },
    {
      "slug": "world-models-paper",
      "title_en": "World Models popularizes the term",
      "title_zh": "World Models 让这一术语走入主流",
      "date": "2018-03-27",
      "description_en": "The World Models paper gives the field a durable conceptual framing.",
      "description_zh": "World Models 论文为该方向提供了持久的概念框架。",
      "event_type": "paper",
      "related_paper_slugs": [
        "world-models-2018"
      ],
      "related_project_slugs": [],
      "related_org_names": [
        "Independent"
      ],
      "why_it_matters": "Many later discussions still trace back to this framing.",
      "featured": true
    }
  ]
} as const;
